[workspace]
resolver = "2"
members = [
    "crates/ron2",
    "crates/ron-schema",
    "crates/ron-derive",
    "crates/ron-lsp",
    "crates/ronfmt",
    "examples/showcase",
    "examples/pretty-errors-miette",
    "examples/pretty-errors-ariadne",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/torkleyy/ron-extras"

[workspace.dependencies]
ron2 = { path = "crates/ron2" }
ron-schema = { path = "crates/ron-schema" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
