[workspace]
resolver = "2"
members = ["crates/ron-schema", "crates/ron-derive", "crates/ron-lsp"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/torkleyy/ron-extras"

[workspace.dependencies]
ron = { path = "ron" }
ron-schema = { path = "crates/ron-schema" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
