[package]
name = "ron-showcase"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ron2 = { path = "../../crates/main" }
ron2-derive = { path = "../../crates/derive" }
ariadne = "0.6"

[profile.release]
debug = true  # Enable debug symbols for profiling
